List<String> demoBigImages = [
  "image/grocery2.jpg",
  "image/grocery4.jpg",
  "image/Groceryg.jpg",
  "image/thew.jpg",
];

List<Map<String, dynamic>> demoMediumCardData = [
  {
    "name": "Penne Pesto",
    "image": "image/penne.jpg",
    "location": "Food Network",
    "rating": 4.6,
    "deliverTime": 25,
    "ingre1": "2 cups fresh basil,",
    "ingre2": "2 cloves garlic",
    "ingre3": "1/4 cup pine nuts",
    "ingre4": "1/2 cup extra-virgin olive oil",
    "ingre5": "1/2 cup freshly grated Parmesan",
    "ingre6": "1/2 teaspoon kosher salt",
    "ingre7": "Freshly ground black pepper",
    "ingre8": "1 pound small tube pasta",
    "instruc1": "Blend basil, garlic, pinenuts, salt, pepper, olive oil",
    "instruc2": "While blending boil pasta till ready",
    "instruc3": "Drain pasta and mix parmesean with blended",
  },
  {
    "name": "Honey Galazed Salmon",
    "image": "image/salmon.jpg",
    "location": "The Chunky Chef",
    "rating": 4.9,
    "deliverTime": 18,
    "ingre1": "4 (6 oz each) salmon filets",
    "ingre2": "1/2 tsp kosher salt",
    "ingre3": "1/2 tsp black pepper",
    "ingre4": "1/2 tsp smoked paprika",
    "ingre5": "1 Tbsp sriracha sauce",
    "ingre6": "6 cloves garlic ",
    "ingre7": "1/2 cup honey",
    "ingre8": "3 Tbsp soy sauce",
    "instruc1": "Add butter, oil, honey, siracha, garlic, into hot pan",
    "instruc2": "Add in salmon and cook for 3 min. Baste frequently",
    "instruc3": "Broil Salmon for 6 minutes, basting with sauce.",
  },
  {
    "name": "Garlic Butter Rice",
    "image": "image/rice.jpg",
    "location": "Cooking Classy",
    "rating": 5.0,
    "deliverTime": 35,
    "ingre1": "4 tablespoons butter",
    "ingre2": "5 cloves garlic",
    "ingre3": "1 1/2 cups uncooked white rice",
    "ingre4": "1 teaspoon dried parsley",
    "ingre5": "1/2 teaspoon salt",
    "ingre6": "1/4 teaspoon fresh cracked black pepper",
    "ingre7": "1/4 teaspoon peprika",
    "ingre8": "1/3 teaspoon water",
    "instruc1": "Melt butter and add garlic and rice. Bring to boil",
    "instruc2": "Add broth, parsley, salt, pepper. Cover with lid",
    "instruc3": "Stir regularly for next 15 min until cooked",
  },
  {
    "name": "Fudgy Brownies",
    "image": "image/brownie.jpg",
    "location": "Inspired Taste",
    "rating": 4.8,
    "deliverTime": 45,
    "ingre1": "10 tablespoons unsalted butter",
    "ingre2": "1 1/4 cups granulated sugar",
    "ingre3": "3/4 cup plus 2 tablespoons unsweetened cocoa powder",
    "ingre4": "1/2 cup (65 grams) all-purpose flour",
    "ingre5": "1/4 teaspoon salt",
    "ingre6": "1 teaspoon vanilla extract",
    "ingre7": "2 large cold eggs",
    "ingre8": "2/3 cup chopped walnuts or pecans, optional",
    "instruc1": "Preheat oven to 325 and combine all ingreidiants",
    "instruc2": "Evenly pour out batter into 8x8 inch square pan",
    "instruc3": "Cook for 20-30 (till toothpick has few crumbs) ",
  },
];
List<Map<String, dynamic>> demoBottomCardData = [
  {
    "name": "Lemonade",
    "image": "image/lemon.jpg",
    "location": "Serious Eats",
    "rating": 4.3,
    "deliverTime": 15,
    "ingre1": "1 cup sugar (can reduce to 3/4 cup)",
    "ingre2": "1 cup water (for the simple syrup)",
    "ingre3": "1 cup freshly squeezed lemon juice",
    "ingre4": "2 to 3 cups cold water, to dilute",
    "ingre5": "1 lime freshly squeezed",
    "ingre6": "",
    "ingre7": "",
    "ingre8": "",
    "instruc1": "Mix sugar and water in saucepan till disolved ",
    "instruc2": "Freshly squeeze the lemons and limes",
    "instruc3": "Combine the simple syrup, water and lemon juice ",
  },
  {
    "name": "Strawberry Milk",
    "image": "image/sm.jpeg",
    "location": "Baking Mischief",
    "rating": 5.0,
    "deliverTime": 15,
    "ingre1": "2 cups milk ",
    "ingre2": "1/2 cup hulled and chopped strawberries",
    "ingre3": "1/4 cup (50g) granulated sugar",
    "ingre4": "1/4 cup water",
    "ingre5": "A couple drops of red food coloring (optional)",
    "ingre6": "",
    "ingre7": "",
    "ingre8": "",
    "instruc1": "Combine water, sugar, strawberries and cook for 10 min ",
    "instruc2": "Use strainer and strain strawberry syrup",
    "instruc3": "Combine milk and strawbery syrup to liking ",
  },
  {
    "name": "Horchata",
    "image": "image/horch.jpeg",
    "location": "Simply Recipies",
    "rating": 4.6,
    "deliverTime": 80,
    "ingre1": "6 cups water ",
    "ingre2": "1 (3-inch) cinnamon stick",
    "ingre3": "1 1/2 cups long-grain white rice",
    "ingre4": "1 (14-ounce) can sweetened condensed milk",
    "ingre5": "1 teaspoon vanilla extract",
    "ingre6": "",
    "ingre7": "",
    "ingre8": "",
    "instruc1": "Boil water with cinnamo stick, rinse rice and blend both",
    "instruc2": "Strain mixture and condenced milk",
    "instruc3": "Stir till smooth and refigerate",
  },
  {
    "name": "Strawberry Banana Smoothie",
    "image": "image/sb.jpeg",
    "location": "Live Eat Learn",
    "rating": 4.7,
    "deliverTime": 25,
    "ingre1": "2 cups frozen strawberries",
    "ingre2": "1 fresh banana, peeled",
    "ingre3": "1 cup milk",
    "ingre4": "1 cup ice",
    "ingre5": "1/2 cup of plain (or vanilla) Greek yogurt",
    "ingre6": "",
    "ingre7": "",
    "ingre8": "",
    "instruc1": "In a blender combine strawberries, bananas, and milk ",
    "instruc2": "Once blended add yogurt and ice",
    "instruc3": "Pour into cup and enjoy",
  },
];
